### ISSUE TITLE
Received durations have no information about origin

### ISSUE THREAD

**Issue by hfxbse** [hfxbse/SportBuzzer#2]
When receiving a duration from the other buzzer, the duration does not have any information about the mode it originated from. This causes a duration from the timer mode to be shown as the result of the stopwatch on the other buzzer. 

This is a bad behavior as everything else requires you to be in the same mode as the other buzzer. Besides confusion, it also creates displaying issues, as the durations from the timer can also be negative.

To fix this, splitting the duration signal into two different, which are doing the same thing, but also storing the signal type should be sufficient, and would require little work.

The same issue exists for the cancel signal.

**Comment by StuBITtv** [comment]
fixed with 80fd3011a6d2df23198c828a03be3c4240e2669d like described above.
